commands = [
  { savefile_manager = "o", hotkey_back = "q", hotkey_close = "escape" },
  { flag = "player_no_goods_consume", hotkey = "1" },
  { flag = "player_no_resource_item_consume", hotkey = "1" },
  { flag = "player_no_revival_consume", hotkey = "1" },
  { flag = "player_hide", hotkey = "2" },
  { flag = "player_silence", hotkey = "2" },
  { flag = "player_no_dead", hotkey = "3" },
  { flag = "player_exterminate", hotkey = "4" },
  { flag = "player_exterminate_stamina", hotkey = "5" },
  { flag = "all_no_dead" },
  { flag = "all_no_damage", hotkey = "6" },
  { flag = "all_no_hit" },
  { flag = "all_no_attack" },
  { flag = "all_no_move" },
  { flag = "all_no_update_ai", hotkey = "7" },
  { group = "Positions", commands = [
    { nudge = 1.0, nudge_up = "[", nudge_down = "]" },
    { position = "h", save = "rshift+h" },
    { position = "j", save = "rshift+j" },
    { position = "k", save = "rshift+k" },
  ]},
  { group = "Render Flags", commands = [
    { flag = "debug_render0" },
    { flag = "debug_render1" },
    { flag = "debug_render2" },
    { flag = "debug_render3" },
    { flag = "debug_render4" },
    { flag = "debug_render5" },
    { flag = "debug_render6" },
    { flag = "debug_render7" },
    { flag = "debug_render8" }
  ]},
  { quitout = "P" }
]

[settings]
log_level = "INFO"
display = "0"
dxgi_debug = false
show_console = false
indicators = [
  { indicator = "game_version", enabled = true },
  { indicator = "igt", enabled = true },
  { indicator = "position", enabled = false },
  { indicator = "framecount", enabled = false },
  { indicator = "imgui_debug", enabled = false }
]